### ISSUE TITLE
Support local docker lambda containers

### ISSUE THREAD

**Issue by zvictor** [jkyberneees/http-lambda-proxy#1]
Do you know how I could use http-lambda-proxy in local lambda deployments?

I noticed that under the hood it makes a call to aws-sdk's `invoke`, but I use [lambci](https://github.com/lambci/docker-lambda) to simulate lambda locally. I don't know if the 2 of them [can work well together](https://github.com/lambci/docker-lambda/issues/30).

---

_@jkyberneees your work is fantastic and it surprises me that so few people were lucky to find it. I really hope it changes and these projects become popular!_

**Comment by zvictor** [comment]
I think I found a way, but it feels weird.

```js
const gateway = require('fast-gateway')

const getLambdaProxy = (config) => (params, cb) => new AWS.Lambda(config).invoke(params, cb)

const name = `service`
const endpoint = `http://localhost:9001`

const server = gateway({
  routes: [{
    proxyType: 'lambda',
    prefix: `/${name}/`,
    target: name,
    lambdaProxy: {
      lambdaProxy: getLambdaProxy({
        endpoint: new AWS.Endpoint(endpoint),
        region: 'any', // Region needs to be a non empty string, even though it's not used in local environment;
        accessKeyId: process.env.LAMBDA_ACCESS_KEY, // same for accessKeyId as well;
        secretAccessKey: process.env.LAMBDA_SECRET_KEY, // and secretAccessKey also!
      }),
    },
  }]
})
```

Considerations and improvement suggestions:

* It requires `region`, `accessKeyId`, and `secretAccessKey` to be defined. The current implementation of `getLambdaProxy` inside `http-lambda-proxy` only receives `region`, so it would be good to reconsider its signature.
https://github.com/jkyberneees/http-lambda-proxy/blob/429b12592df115664ae959506c44f9587af0245d/index.js#L78-L80

* `routes.lambdaProxy.lambdaProxy` is very weird. Something should be done to simplify the [customizations coming from fast-gateway](https://github.com/jkyberneees/fast-gateway/blob/8da03dd032d70cc23c0078d459917cabb6fed3b7/lib/proxy-factory.js#L17).

**Comment by jkyberneees** [comment]
Hi @zvictor, many thanks for your feedback and deep dive into this project. 
I also agree with your suggestions on improvements, will followup with a PR ASAP.

Regards

**Comment by jkyberneees** [comment]
Hi @zvictor, may I have your opinion on this: https://github.com/jkyberneees/http-lambda-proxy/pull/2 ?
Thanks

**Comment by zvictor** [comment]
I think it's a good improvement, but still a bit clumsy. Would I need to define the route like below?

```js
{
    proxyType: 'lambda',
    prefix: `/${name}/`,
    target: name,
    lambdaProxy: {
      region: 'any',
      sdkConfig: {
        endpoint: new AWS.Endpoint(endpoint),
        accessKeyId: process.env.LAMBDA_ACCESS_KEY,
        secretAccessKey: process.env.LAMBDA_SECRET_KEY,
      },
    },
  }
```

It looks like we could kill the `sdkConfig` completely, no? Let me push a little proposal as well. 🙂

**Comment by jkyberneees** [comment]
This feature  is now supported https://github.com/jkyberneees/http-lambda-proxy/releases/tag/v1.1.0
